services:
  nginx:
    image: nginx
    container_name: 'nginx_api_gateway'
    ports:
      - '9000:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
  auth_svc:
    image: nginx-learn_auth_service:alpine
    container_name: 'auth_service'
    build:
      context: .
      dockerfile: Dockerfile.auth_service
      target: prod
    ports:
      - '9001:9001'
  user_svc:
    image: nginx-learn_user_service:alpine
    container_name: 'user_service'
    build:
      context: .
      dockerfile: Dockerfile.user_service
      target: prod
    ports:
      - '9002:9002'
